; ##########################################################################
; PlatformIO Configuration File for Project
; Armario Técnico de Seguridad - KinCony KC868-A16 v3.1 (ESP32-S3)
; Fecha: 23 de Enero de 2026
; ##########################################################################

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags = 
    -D VERSION_AUTO=\"${sysenv.GITHUB_RUN_NUMBER}\"
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D W5500_MISO=12
    -D W5500_MOSI=11
    -D W5500_SCLK=13
    -D W5500_CS=14
    -D W5500_RST=9
    -D W5500_INT=10
    -D SD_CS=4
    -D SD_MOSI=6
    -D SD_MISO=5
    -D SD_SCLK=7    
    -D arduino_h=Arduino_h
    -include Arduino.h
    -I .pio/libdeps/esp32-s3-devkitc-1/DFRobot_BMI160

    
lib_deps =
    arduino-libraries/Ethernet @ ^2.0.2
    adafruit/Adafruit BusIO @ ^1.14.1
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    adafruit/Adafruit SHT4x Library @ ^1.0.2
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/RTClib @ ^2.1.3
    dfrobot/DFRobot_BMI160 @ ^1.0.0
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.1
    adafruit/Adafruit NeoPixel @ ^1.12.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    4-20ma/ModbusMaster @ ^2.0.1
    starmbi/hp_BH1750 @ ^1.0.2
